###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=112233
        - MYSQL_DATABASE=balance_service
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "9990:3306"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      ports:
        - "9001:9002"
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    
    nginx:
      image: nginx:1.15.0
      container_name: nginx
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "7777:80"
      depends_on:
        - php-fpm
      links:
        - php-fpm
        
    rabbitmq:
      image: 'rabbitmq:3.6-management-alpine'
      container_name: rabbitmq
      working_dir: /application
      ports:
        - '5672:5672'
        - '15672:15672'

